[env:disco_b_g431b_esc1]
platform = ststm32
board = disco_b_g431b_esc1
framework = arduino
monitor_speed = 115200
lib_archive = false

build_flags =
    -D HAL_OPAMP_MODULE_ENABLED
    -D HAL_CORDIC_MODULE_ENABLED
    -D PIN_WIRE_SDA=PB7
    -D PIN_WIRE_SCL=PB8

lib_deps =
    askuric/Simple FOC @ ^2.3.3